# Generated by Django 4.0.5 on 2022-06-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LANGUAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('id_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CALENDAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.ImageField(default='static/DC_Comics_logo.png', upload_to='')),
                ('check_mark', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
                ('author', models.CharField(default='None', max_length=15)),
                ('calendarID', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineStoreOfCalendars.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineStoreOfCalendars.language')),
            ],
        ),
    ]
